import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import AuthProvider from '@/SessionProvider'
import { ThemeContextProvider } from '@/lib/ThemeContext'
import ThemeProvider from '@/lib/ThemeProvider'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
           <div className='dark:bg-grey'>
           <Navbar />
              {children}
              <Footer />
           </div>
            </ThemeProvider>
          </ThemeContextProvider>
       </AuthProvider>
        </body>
    </html>
  )
}
